### ISSUE TITLE
"BUGS" dropdown menu

### ISSUE THREAD

**Issue by KEYS248** [BUGS-NYU/test_site#10]
- [x] the "BUGS" word in the dropdown menu in each page should be clickable and return you to the homepage
- [x] also the "About" section from the homepage should be included in the dropdown menu

**Comment by cr4zyafrican** [comment]
I agree we should move the about and Mozilla Affiliation tab to the top with the rest of the tabs.

**Comment by KEYS248** [comment]
I've resolved the first issue! Nadz resolved the 2nd
