### ISSUE TITLE
The pixelated font is not very visually pleasing to look at

### ISSUE THREAD

**Issue by VeenaArv** [BUGS-NYU/test_site#15]
I suggest using a simpler, cleaner font.

**Comment by S1MB10T3** [comment]
The font on the design mock up isn't what we are using on the actual site. I think I'm using open sans for paragraph text. I don't remember at this current moment.

You can check out a working build of the site here:
https://bugs-nyu.github.io/test_site/

**Comment by KEYS248** [comment]
We've changed the headers (except h1 and h2) to be a very heavy sans-serif
