### ISSUE TITLE
mock design images

### ISSUE THREAD

**Issue by S1MB10T3** [BUGS-NYU/test_site#18]
Noticing that a handful of the reported issues are based off the mock design images in the readme. I've made some changes in the design of the site in the current code base, but didn't create a update mockup image for the readme.

We can ether:
1. redesign the mock images
2. remove mock design images from the readme

I personally interested of remaking a mockup image. Making them everytime we make a design change would be a pain. If you peeps feel that we should tinker or rework the design we to set a meeting to dicuss the design choices/philosophy for the site.

**Comment by KEYS248** [comment]
@Rantahu I don't think we need mockups anymore now that they've been implemented, hosted online, and improved upon. Only if we are going to be doing broad and significant changes to the design would we need to make new ones. I think #15 and #16 are about the "Press Start 2P" font which I am a personal fan of and vote to stay, but for appeasement is it possible to easily change the current "Press Start 2P" font to one less pixelated but still retro one to see how it looks on the site? Then we could vote, make a decision, and close these issues

**Comment by KEYS248** [comment]
Closing this issue since I've closed #15  and #16
