### ISSUE TITLE
Description of projects should be switched to one tense

### ISSUE THREAD

**Issue by VeenaArv** [BUGS-NYU/test_site#24]
Right now, the description for the projects are all over the place (I'm guessing because it was written by the mentors). I feel like we should go and edit the descriptions to one tense and make it overall more uniform.

**Comment by KEYS248** [comment]
@VeenaArv could you take charge on this issue? and have you been in contact with project mentors and would you be able to help with the other issue #25 ? also your contributions should be to our new place in [the main website repo](https:/www.github.com/bugs-nyu/bugs-nyu.github.io)

**Comment by KEYS248** [comment]
actually I've updated the website's projects as such! thank you for the issue
